image: gitpod/workspace-full:latest

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000-8999
    onOpen: "notify"
    visibility: "public"

# List of VS Code extensions to be installed
vscode:
  extensions:
    - ms-dotnettools.csharp
    - anwar.papyrus-pdf

# Commands to run on start
tasks:
  - init: echo 'Initialization commands can go here'
    command: echo 'Startup commands like running your app can go here'
